### ISSUE TITLE
Error with conflicting URI templates

### ISSUE THREAD

**Issue by markpatton** [jhu-sheridan-libraries/stfrancis-lutece-site#6]
From the tomcat logs in deployment:

```
SEVERE: Conflicting URI templates. The URI template /rest/enroll/api/v{version}/projects for root resource class fr.paris.lutece.plugins.enroll.rs.EnrollmentRest and the URI template /rest/enroll/api/v{version}/projects transform to the same regular expression /rest/enroll/api/v([^/]+?)/projects(/.*)?
05/12/19 15:36:39 ERROR [Lutece-MainThread] lutece.rest - REST services won't be available. Please check your configuration or enable at least on rest module.
05/12/19 15:36:39 ERROR [Lutece-MainThread] lutece.rest - LuteceJerseySpringServlet : Exception occurred when intialization
com.sun.jersey.spi.inject.Errors$ErrorMessagesException
    at com.sun.jersey.spi.inject.Errors.processErrorMessages(Errors.java:170)
    at com.sun.jersey.spi.inject.Errors.postProcess(Errors.java:136)
    at com.sun.jersey.spi.inject.Errors.processWithErrors(Errors.java:199)
    at com.sun.jersey.server.impl.application.WebApplicationImpl.initiate(WebApplicationImpl.java:795)
    at fr.paris.lutece.plugins.rest.service.LuteceJerseySpringServlet.initiate(LuteceJerseySpringServlet.java:138)
    at com.sun.jersey.spi.container.servlet.ServletContainer$InternalWebComponent.initiate(ServletContainer.java:321)
    at com.sun.jersey.spi.container.servlet.WebComponent.load(WebComponent.java:605)
    at com.sun.jersey.spi.container.servlet.WebComponent.init(WebComponent.java:207)
    at com.sun.jersey.spi.container.servlet.ServletContainer.init(ServletContainer.java:376)
    at com.sun.jersey.spi.container.servlet.ServletContainer.init(ServletContainer.java:726)
    at fr.paris.lutece.portal.service.filter.FilterService.init(FilterService.java:143)
    at fr.paris.lutece.portal.service.init.AppInit.initServices(AppInit.java:186)
    at fr.paris.lutece.portal.service.init.AppInitListener.contextInitialized(AppInitListener.java:73)
    at org.apache.catalina.core.StandardContext.listenerStart(StandardContext.java:4699)
    at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5165)
    at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183)
    at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:743)
    at org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:719)
    at org.apache.catalina.core.StandardHost.addChild(StandardHost.java:705)
    at org.apache.catalina.startup.HostConfig.deployWAR(HostConfig.java:970)
    at org.apache.catalina.startup.HostConfig$DeployWar.run(HostConfig.java:1841)
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
    at java.util.concurrent.FutureTask.run(FutureTask.java:266)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
    at java.lang.Thread.run(Thread.java:748)
```

**Comment by jrmartino** [comment]
removed unused class EnrollmentRest and creation of its bean
