### ISSUE TITLE
Internal Server Error when accessing Technical Admin function

### ISSUE THREAD

**Issue by jrmartino** [jhu-sheridan-libraries/stfrancis-lutece-site#7]
When logged in as admin, trying to access the Technical Admin function results in this error:

```
Internal error 
Unfortunately, the website (or link) you are trying to access is not working at the moment. Please contact the website's (or link's) administrator for more information.
'''

The tomcat log stack trace shows:

```
 05/12/19 15:43:36 ERROR [http-nio-8080-exec-5] lutece.error - For "${...}" content: Expected a string or something automatically convertible to string (number, date or boolean), or "template output" , but this has evaluated to a macro+misc_template_model (wrapper: f.c.Macro):
tomcat         | ==> icon!  [in template "admin/plugins/form/form_admindashboard.html" at line 3, column 29]
tomcat         | 
tomcat         | ----
tomcat         | FTL stack trace ("\~" means nesting-related):
tomcat         | 	- Failed at: ${icon!}  [in template "admin/plugins/form/form_admindashboard.html" at line 3, column 27]
tomcat         | ----
tomcat         | java.lang.RuntimeException: For "${...}" content: Expected a string or something automatically convertible to string (number, date or boolean), or "template output" , but this has evaluated to a macro+misc_template_model (wrapper: f.c.Macro):
tomcat         | ==> icon!  [in template "admin/plugins/form/form_admindashboard.html" at line 3, column 29]
tomcat         | 
tomcat         | ----
tomcat         | FTL stack trace ("\~" means nesting-related):
tomcat         | 	- Failed at: ${icon!}  [in template "admin/plugins/form/form_admindashboard.html" at line 3, column 27]
tomcat         | ----
tomcat         | 	at fr.paris.lutece.portal.service.template.AbstractFreeMarkerTemplateService.processTemplate(AbstractFreeMarkerTemplateService.java:305)
tomcat         | 	at fr.paris.lutece.portal.service.template.AbstractFreeMarkerTemplateService.loadTemplate(AbstractFreeMarkerTemplateService.java:188)
tomcat         | 	at fr.paris.lutece.portal.service.template.AppTemplateService.loadTemplate(AppTemplateService.java:254)
tomcat         | 	at fr.paris.lutece.portal.service.template.AppTemplateService.getTemplate(AppTemplateService.java:208)
tomcat         | 	at fr.paris.lutece.portal.service.template.AppTemplateService.getTemplate(AppTemplateService.java:184)
tomcat         | 	at fr.paris.lutece.plugins.form.web.FormAdminDashboardComponent.getDashboardData(FormAdminDashboardComponent.java:74)
tomcat         | 	at fr.paris.lutece.portal.service.dashboard.admin.AdminDashboardService.getDashboardData(AdminDashboardService.java:336)
tomcat         | 	at fr.paris.lutece.portal.web.dashboard.AdminDashboardJspBean.getAdminDashboards(AdminDashboardJspBean.java:113)
```

The offending line in the file `WEB-iNF/templates/admin/plugins/form/form_admindashboard.html` is

` <!-- img src="${icon!}" title="logo #i18n{document.dashboard.labelDocument}" alt="logo #i18n{document.dashboard.labelDocument}"/ -->
`
Deleting the offending line in the exploded war, repackaging and redeploying stops the error from occurring.

**Comment by jrmartino** [comment]
This issue seems to go away for some reason if we fix the rest URI mapping issue by not creating the enrollment REST bean

**Comment by jrmartino** [comment]
this went away after closing a seemingly unrelated issue for URI collison
